### ISSUE TITLE
ACAM | Legendgod's Blog

### ISSUE THREAD

**Issue by legendgoddess** [legendgoddess/Blog#5]
https://legendgod.ml/2021/11/08/ACAM/ 

 浅谈AC自动机   建议学过 AC 自动机的人来看。  注意我们一开始直接建立串的时候是 $\tt Trie$ 图，之后建立 $\tt fail$ 指针的时候才是真正的 $AC$ 自动机。 具体来说对于 $\tt Trie$ 上深度从小到大的一条链，对应的是一个曾经在某个或者多个串中出现过的子串。 如果说是一条从根到底的链那本质就是代表一个串，显然对于一条链之间的点，本质上深度小的是深度大的前缀串

**Comment by legendgoddess** [comment]
$orz$

**Comment by legendgoddess** [comment]
```cpp
orz
```

**Comment by Ruakker** [comment]
%%%
